Fixes #48 | Add gulpfile#48
CoWare/Licit pull request #49
Opened 2016-09-22 20:16 UTC by cyrielo

This PR adds functionality for automating eslint using gulp task

2016-09-22 20:51 UTC, andela-rekemezie commented on package.json
> +    "lint": "node node_modules/gulp/bin/gulp eslint",
What are you trying to achieve here? use `gulp lint`.
Define your task as lint. And remember to install gulp globally on your system.

2016-09-22 20:51 UTC, andela-rekemezie commented on gulpfile.js
> +});
EOF. install editorConfig in your text editor

2016-09-22 20:51 UTC, rowlandekemezie requested changes

2016-09-23 07:32 UTC, cyrielo commented on package.json
> +    "lint": "node node_modules/gulp/bin/gulp eslint",
I was trying was to make sure the `npm lint` command works even if you don't have gulp installed globally

2016-09-23 07:35 UTC, andela-rekemezie commented on package.json
> +    "lint": "node node_modules/gulp/bin/gulp eslint",
Yes. My check is why you're using `node node_modules/gulp/bin/` in the first place. We want it to be simply.

2016-09-23 07:35 UTC, andela-rekemezie commented on package.json
> +    "lint": "node node_modules/gulp/bin/gulp eslint",
Can you fix that straight up

2016-09-23 07:36 UTC, cyrielo commented on package.json
> +    "lint": "node node_modules/gulp/bin/gulp eslint",
Sure

2016-09-23 07:47 UTC, cyrielo commented on gulpfile.js
> +});
Had it installed but not configured, formatted my code now. Thanks

2016-09-23 07:51 UTC, rowlandekemezie approved these changes

2016-09-23 08:33 UTC, merged