fixes #37 |  Update documents  hyperlinks
CoWare/Licit pull request #54
Opened 2016-09-25 02:35 UTC by andela-rekemezie

This PR updates #53 because some hyperlinks weren't working.

2016-09-25 21:12 UTC, adetolaraphael commented on README.md
> +Refer to [Contibuting Docuemnent](./docs/CONTRIBUTING.MD) to contribute to this project.
Typo error in` [Contibuting Document]`. Meant to be `[Contributing Document]`. @andela-rekemezie

2016-09-25 21:14 UTC, ghost requested changes
Some typo errors on line 50 in the README.md file.

2016-09-25 21:37 UTC, andela-rekemezie commented on README.md
> +Refer to [Contibuting Docuemnent](./docs/CONTRIBUTING.MD) to contribute to this project.
Thanks! 
Fixed

2016-09-27 21:43 UTC, andela-abisoye commented
What do we need a contribution.md and a waffle.md document for?

2016-09-28 06:01 UTC, andela-rekemezie commented
@Saint-lawal To help people contribute to the project. Check develop branch and see it's usefulness. In the meantime, approve the PR if you can.

2016-09-28 06:03 UTC, andela-rekemezie commented on README.md
> +Refer to [Contibuting Docuemnent](./docs/CONTRIBUTING.MD) to contribute to this project.
@adetolaraphael the changes you requested has been fixed. Simply approved or request for more changes and I'd merge the issue.

2016-09-29 15:06 UTC, ghost approved these changes

2016-09-29 15:08 UTC, merged